import { iransans, vazirmatn, vazirmatnNumbers, yekanBakh } from "@/utils/fonts";
import "./globals.css";
import Layout from "@/components/layout/Layout";
import ReactQueryProvider from "@/components/partials/provider/ReactQueryProvider";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import { ToastContainer } from "react-toastify";
//yekan bakh 400
//yekan bakh 600
//vazir FD-WOL 400
//vazir FD-WOL 700
//vazir matn 800
//vazir FD-WOL 500
//vazir FD-WOL 300

export const metadata = {
  title: "تورینو | تورگردی متمایز",
  description:"وب سایت تورینو یک وبسایت آزمایشی رزرو تور های مسافرتی به صورت کاملا برخط و آنلاین با پشتیبانی 24 ساعته آماده این است تا تجربه ای متفاوت را به شما هدیه دهد.",
  keywords:"توررینو ،رزرو اینترنتی ،برگزاری تور،تور های مسافرتی ،خدمات تفریحی ،کسب و کار بین المللی،جاذبه های طبیعی ،گردشگری و توریست",
  author:"Mohammad Saber Khanpayeh",
  icons:{
    icon: "/favicon/icon.ico",
    shortcut:"/favicon/icon.png"
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children,auth }) {
  return (
    <html
      lang="fa"
      dir="rtl"
      className={`${yekanBakh.variable} ${vazirmatn.variable} ${vazirmatnNumbers.variable} ${iransans.variable}`}
    >
      <body>
        <ReactQueryProvider>
        <Layout>{children}{auth??null}
          <ToastContainer/>
        </Layout>
        <ReactQueryDevtools/>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
